const app = document.getElementById('app');
const toast = document.getElementById('toast');
const modal = document.getElementById('modal');
const modalContent = document.getElementById('modalContent');
const roomTypes = [
 {name:'Estándar (Doble / Individual)',category:'Estándar',capacity:2,price:2400,img:'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1000&q=85',desc:'Ofrece comodidad esencial con diseño colonial y amenidades modernas.',details:'Habitación confortable con cama matrimonial o dos individuales, baño privado, aire acondicionado y Wi-Fi.'},
 {name:'Familiar',category:'Familiar',capacity:4,price:3200,img:'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=85',desc:'Un espacio amplio diseñado para albergar un máximo de 4 personas, ideal para viajes en familia.',details:'Espacio amplio, ideal para familias, con dos camas y áreas cómodas para descansar.'},
 {name:'Suite / Junior Suite',category:'Suite',capacity:2,price:4800,img:'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=85',desc:'Representa el máximo lujo, amplitud y vistas exclusivas con detalles en acento dorado.',details:'Suite con diseño distintivo, área de descanso amplia y amenidades premium.'}
];
const amenities = [
 {name:'Restaurante',desc:'Gastronomía local e internacional con un toque contemporáneo.',img:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=85',cta:'Explorar espacio'},
 {name:'Jardín Interior',desc:'Un oasis de tranquilidad arquitectónica en medio de la muralla.',img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85',cta:'Explorar espacio'},
 {name:'Spa y Sauna',desc:'Espacios diseñados para la relajación profunda y el bienestar.',img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=85',cta:'Explorar espacio'},
 {name:'Roof Garden',desc:'Vistas panorámicas incomparables al atardecer de Campeche.',img:'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1000&q=85',cta:'Explorar espacio'}
];
const dishes = [
 {name:'Pulpo a la Campechana',desc:'Pulpo fresco con cítricos, hierbas locales y un toque contemporáneo.',img:'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=1000&q=85',kind:'principal'},
 {name:'Pesca del Día',desc:'Selección fresca de la costa, acompañada de guarniciones de temporada.',img:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1000&q=85',kind:'principal'},
 {name:'Cochinita de Autor',desc:'Receta tradicional reinterpretada con especias regionales y presentación contemporánea.',img:'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=85',kind:'principal'},
 {name:'Postre Saasil',desc:'Dulce de inspiración local con texturas delicadas y acabado elegante.',img:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=85',kind:'principal'},
 {name:'Agua fresca de temporada',desc:'Fruta fresca, notas cítricas y preparación del día.',img:'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1000&q=85',kind:'bebida'},
 {name:'Cóctel de la Casa',desc:'Mezcla de autor con ingredientes de inspiración peninsular.',img:'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1000&q=85',kind:'bebida'}
];
const services = [
 {name:'Spa y Masajes Relajantes',desc:'Sesiones personalizadas para una relajación profunda del cuerpo y la mente.',img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=85',cta:'Solicitar servicio'},
 {name:'Diseño de Arte',desc:'Experiencias visuales y talleres creativos inspirados en la identidad cultural e historia local.',img:'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=85',cta:'Reservar experiencia'},
 {name:'Guía Turístico Especializado',desc:'Recorridos privados y guiados por los baluartes, murallas y rincones históricos de la ciudad.',img:'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1000&q=85',cta:'Reservar experiencia'},
 {name:'Atención y Conserjería Personalizada',desc:'Asistencia a tu medida para hacer de tu estancia una vivencia inolvidable.',img:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=85',cta:'Solicitar servicio'}
];
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3200)}
function money(n){return n.toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0})}
function card(item,cls='feature-card',buttonLabel='Ver detalles',type='info'){return `<article class="card ${cls}"><img class="card-image" src="${item.img}" alt="${item.name}" loading="lazy"><div class="card-body"><div class="mini-rule"></div><h3>${item.name}</h3><p>${item.desc}</p><div class="actions"><button class="btn btn-small" data-action="${type}" data-name="${item.name}">${buttonLabel}</button></div></div></article>`}
function intro(eyebrow,title,description){return `<section class="page-intro center"><div class="container"><div class="eyebrow">${eyebrow}</div><h1 class="section-heading">${title}</h1><p class="subheading">${description}</p></div></section>`}
function home(){return `<section class="hero"><div class="hero-inner"><div class="hero-frame"><div class="eyebrow" style="color:#f1cb4e">Hotel Boutique · Campeche</div><h1>Hospitalidad Exclusiva en la Ciudad Amurallada</h1><p>Escápate al corazón de Campeche y vive una experiencia única de descanso y tradición en Kiin Saasil.</p></div></div></section><form class="booking-bar" id="availabilityForm"><div class="field"><label for="checkin">Check-in</label><input id="checkin" type="date" required></div><div class="field"><label for="checkout">Check-out</label><input id="checkout" type="date" required></div><div class="field"><label for="guests">Huéspedes</label><select id="guests"><option value="2">2 adultos · 0 niños</option><option value="1">1 adulto</option><option value="3">3 huéspedes</option><option value="4">4 huéspedes</option></select></div><button class="btn" type="submit">Consultar disponibilidad</button></form><section class="home-section container"><div class="split-heading"><div><div class="eyebrow">Lugares y amenidades</div><h2>Espacios pensados para el descanso</h2></div><p>Entre muros centenarios y patios llenos de luz, cada rincón de Kiin Saasil invita a bajar el ritmo y descubrir los sabores y tradiciones de Campeche.</p></div><div class="grid grid-2">${amenities.slice(0,2).map(x=>card(x,'feature-card','Explorar espacio','amenity')).join('')}</div><div class="actions" style="justify-content:center;margin-top:24px"><a class="btn btn-outline" href="#amenidades">Conocer todas las amenidades</a></div></section><section class="home-section container"><div class="split-heading"><div><div class="eyebrow">Estancia a tu medida</div><h2>Nuestras habitaciones y suites</h2></div><p>Espacios diseñados para el descanso con el equilibrio perfecto entre tradición colonial y confort moderno.</p></div><div class="grid grid-3">${roomTypes.map(roomCard).join('')}</div></section>`}
function roomCard(r){return `<article class="card room-card"><img class="card-image" src="${r.img}" alt="${r.name}" loading="lazy"><div class="card-body"><span class="pill" style="align-self:flex-start">${r.category}</span><h3 style="margin-top:14px">${r.name}</h3><p>${r.desc}</p><div class="room-meta"><div><div class="price-label">DESDE</div><div class="price">${money(r.price)}</div><small>/ noche</small></div><button class="btn btn-small" data-action="room" data-name="${r.name}">Ver detalles</button></div></div></article>`}
function rooms(){return `${intro('Catálogo de habitaciones','Nuestras Habitaciones y Suites','Espacios diseñados para el descanso con el equilibrio perfecto entre tradición colonial y confort moderno.')}<section class="container"><form class="filters" id="roomFilters"><div class="filter-title">☷ &nbsp; Filtros</div><div class="field"><label for="category">Tipo o categoría</label><select id="category"><option value="all">Todas las categorías</option><option>Estándar</option><option>Familiar</option><option>Suite</option></select></div><div class="field"><label for="capacity">Capacidad de huéspedes</label><select id="capacity"><option value="0">Cualquier capacidad</option><option value="2">2 o más huéspedes</option><option value="4">4 huéspedes</option></select></div><div class="field"><label for="priceRange">Rango de precio</label><select id="priceRange"><option value="all">Todos los precios</option><option value="3000">Hasta $3,000</option><option value="4000">Hasta $4,000</option></select></div><button class="btn" type="submit">Aplicar filtros</button><button class="link-button" type="reset">Limpiar filtros</button></form><div class="catalog-top"><strong id="roomCount">3 categorías disponibles</strong><span class="notice">Tarifas de referencia por noche, impuestos incluidos.</span></div><div id="roomGrid" class="grid grid-3">${roomTypes.map(roomCard).join('')}</div></section>`}
function amenityPage(){return `${intro('Portal de huéspedes','Espacios y Amenidades Exclusivas','Descubre los rincones diseñados para tu descanso y desconexión en el corazón de la Ciudad Amurallada.')}<section class="container grid grid-2">${amenities.map(x=>card(x,'feature-card','Explorar espacio','amenity')).join('')}</section>`}
function gastronomy(){return `${intro('Portal de huéspedes','Gastronomía y Coctelería de Autor','Sabores que fusionan la tradición culinaria de Campeche con la alta cocina contemporánea.')}<div class="center"><div class="tabs" role="tablist"><button class="tab active" data-food="principal">Platillos principales</button><button class="tab" data-food="bebida">Bebidas y Coctelería</button></div></div><section class="container" style="padding-top:30px"><div class="center" style="margin-bottom:25px"><div class="eyebrow">Especialidades de la casa</div><h2 id="foodHeading" style="font-size:25px">Platillos Principales</h2><p id="foodDescription">Una carta de autor elaborada con ingredientes del Golfo y la península.</p></div><div id="foodGrid" class="grid grid-2">${dishes.filter(d=>d.kind==='principal').map(d=>card(d,'feature-card','Ver platillo','dish')).join('')}</div></section>`}
function servicePage(){return `${intro('Portal de huéspedes','Experiencias y Servicios Exclusivos','Eleva tu estancia en Campeche con nuestros servicios personalizados diseñados para tu bienestar y descubrimiento cultural.')}<section class="container grid grid-2">${services.map(x=>card(x,'feature-card service-card',x.cta,'service')).join('')}</section>`}
function reservations(){return `${intro('Portal de huéspedes','Consulta de Mis Reservas','Ingresa tu código de confirmación o correo electrónico para verificar el estatus actual de tu estancia.')}<section class="container reservations-layout"><form class="panel" id="reservationSearch"><h3>Consulta rápida</h3><div class="stack"><div class="field"><label for="folio">Folio de reservación</label><input id="folio" placeholder="KS-2026-0000" autocomplete="off"></div><div class="field"><label for="reservationEmail">Correo electrónico</label><input id="reservationEmail" type="email" placeholder="tu-correo@ejemplo.com" autocomplete="email"></div><button class="btn" type="submit">Buscar reservación</button><button class="link-button" id="clearReservation" type="button">Limpiar búsqueda</button></div><div class="help-note">ⓘ Encuentra tu folio en el correo de confirmación. No se muestran reservaciones hasta conectarse con el sistema.</div></form><div><h2 style="font-size:25px">Historial de Estancias</h2><p style="margin-top:5px">Resumen de tus reservaciones en Kiin Saasil.</p><div id="reservationResults" style="margin-top:24px"><div class="empty-state"><div class="empty-icon">⌕</div><h3>Consulta tus reservaciones</h3><p>Ingresa tu folio o correo para buscar tus estancias registradas.</p></div></div></div></section>`}
function authPage(){return `<section class="auth-shell"><div class="auth-image"><div class="brand"><span class="brand-line"></span> KIIN SAASIL</div><div><div class="mini-rule"></div><h2>Tu estancia comienza con una experiencia excepcional.</h2><p>Hotel Boutique · Ciudad Amurallada de Campeche</p></div></div><div class="auth-forms"><section class="auth-card"><div class="auth-switch"><button class="active" data-auth="login">Iniciar Sesión</button><button data-auth="register">Registrarse</button></div><div id="loginFormWrap"><h2>Iniciar Sesión</h2><form id="loginForm"><div class="form-row"><label for="loginUser">Nombre de usuario o número de teléfono</label><input id="loginUser" required autocomplete="username"></div><div class="form-row"><label for="loginPass">Contraseña</label><input id="loginPass" type="password" required autocomplete="current-password"></div><button class="btn" type="submit">Iniciar Sesión</button><p class="auth-note"><a class="link-button" href="#recuperar">¿Olvidaste tu contraseña?</a></p></form></div></section><section class="auth-card"><div class="auth-switch"><button data-auth="login">Iniciar Sesión</button><button class="active" data-auth="register">Registrarse</button></div><div id="registerFormWrap"><h2>Crear Cuenta</h2><form id="registerForm"><div class="form-row"><label for="registerUser">Nombre de usuario</label><input id="registerUser" required autocomplete="username"></div><div class="form-row"><label for="registerPhone">Número de teléfono</label><input id="registerPhone" type="tel" required autocomplete="tel"></div><div class="form-row"><label for="registerEmail">Correo electrónico</label><input id="registerEmail" type="email" required autocomplete="email"></div><div class="form-row"><label for="registerPass">Contraseña</label><input id="registerPass" type="password" minlength="8" required autocomplete="new-password"></div><button class="btn" type="submit">Registrarse</button><p class="auth-note">La creación real de cuentas estará disponible al conectar el backend.</p></form></div></section></div></section>`}
function recovery(){return `<section class="auth-shell recovery-shell"><div class="auth-image"><div class="brand"><span class="brand-line"></span> KIIN SAASIL</div><div><div class="mini-rule"></div><h2>Tu estancia comienza con una experiencia excepcional.</h2><p>Hotel Boutique · Ciudad Amurallada de Campeche</p></div></div><section class="recovery-form"><div class="eyebrow">Portal de huéspedes</div><h1>Recuperar contraseña</h1><p>Ingresa tu correo electrónico o número de teléfono para solicitar instrucciones para restablecer tu contraseña.</p><form id="recoveryForm" style="margin-top:24px"><div class="form-row"><label for="recoveryContact">Correo electrónico o número de teléfono</label><input id="recoveryContact" required placeholder="correo@ejemplo.com o teléfono"></div><button class="btn" type="submit">Enviar enlace de recuperación</button></form><div class="help-note">Por seguridad, el envío del enlace se habilitará cuando el portal esté conectado al backend.</div><p class="center" style="margin-top:22px"><a class="link-button" href="#login">← Volver a Iniciar Sesión</a></p></section></section>`}
const pages={inicio:home,habitaciones:rooms,amenidades:amenityPage,gastronomia:gastronomy,servicios:servicePage,reservas:reservations,login:authPage,recuperar:recovery};
function currentPage(){let p=location.hash.replace('#','').split('?')[0];return pages[p]?p:'inicio'}
function render(){let page=currentPage();app.innerHTML=pages[page]();document.querySelectorAll('#mainNav [data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===page));document.getElementById('mainNav').classList.remove('open');window.scrollTo(0,0);wirePage(page)}
function wirePage(page){
 const checkin=document.getElementById('checkin'),checkout=document.getElementById('checkout');if(checkin&&checkout){const today=new Date();const local=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');checkin.min=local;checkout.min=local;checkin.addEventListener('change',()=>{checkout.min=checkin.value;if(checkout.value&&checkout.value<=checkin.value)checkout.value=''});document.getElementById('availabilityForm').addEventListener('submit',e=>{e.preventDefault();if(checkout.value<=checkin.value){showToast('La salida debe ser posterior a la fecha de entrada.');return}showToast('La consulta de disponibilidad estará disponible al conectar el sistema de reservaciones.');location.hash='habitaciones'})}
 const filterForm=document.getElementById('roomFilters');if(filterForm){const apply=()=>{let cat=document.getElementById('category').value,cap=Number(document.getElementById('capacity').value),price=document.getElementById('priceRange').value;let found=roomTypes.filter(r=>(cat==='all'||r.category===cat)&&(!cap||r.capacity>=cap)&&(price==='all'||r.price<=Number(price)));document.getElementById('roomGrid').innerHTML=found.length?found.map(roomCard).join(''):'<div class="empty-state" style="grid-column:1/-1"><h3>Sin categorías con esos filtros</h3><p>Prueba con otros criterios de búsqueda.</p></div>';document.getElementById('roomCount').textContent=`${found.length} ${found.length===1?'categoría disponible':'categorías disponibles'}`};filterForm.addEventListener('submit',e=>{e.preventDefault();apply()});filterForm.addEventListener('reset',()=>setTimeout(apply,0))}
 document.querySelectorAll('[data-food]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-food]').forEach(x=>x.classList.toggle('active',x===b));let type=b.dataset.food;document.getElementById('foodHeading').textContent=type==='principal'?'Platillos Principales':'Bebidas y Coctelería';document.getElementById('foodDescription').textContent=type==='principal'?'Una carta de autor elaborada con ingredientes del Golfo y la península.':'Bebidas refrescantes y coctelería inspiradas en los sabores de la región.';document.getElementById('foodGrid').innerHTML=dishes.filter(d=>d.kind===type).map(d=>card(d,'feature-card',type==='principal'?'Ver platillo':'Ver bebida','dish')).join('')}));
 const search=document.getElementById('reservationSearch');if(search){search.addEventListener('submit',e=>{e.preventDefault();const folio=document.getElementById('folio').value.trim(),email=document.getElementById('reservationEmail').value.trim();if(!folio&&!email){showToast('Escribe un folio o correo electrónico para buscar.');return}document.getElementById('reservationResults').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>No se pudo consultar la reservación</h3><p>Este prototipo todavía no está conectado a la base de datos. No se inventaron registros de huéspedes ni reservaciones.</p></div>';showToast('La búsqueda requiere conexión con el backend.');});document.getElementById('clearReservation').addEventListener('click',()=>{search.reset();document.getElementById('reservationResults').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>Consulta tus reservaciones</h3><p>Ingresa tu folio o correo para buscar tus estancias registradas.</p></div>'})}
 document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>{const mode=b.dataset.auth;document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('active',x.dataset.auth===mode));document.getElementById('loginFormWrap').style.display=mode==='login'?'block':'none';document.getElementById('registerFormWrap').style.display=mode==='register'?'block':'none'}));
 ['loginForm','registerForm','recoveryForm'].forEach(id=>{let f=document.getElementById(id);if(f)f.addEventListener('submit',e=>{e.preventDefault();if(id==='loginForm')showToast('El inicio de sesión requiere validar las credenciales con el backend.');else if(id==='registerForm')showToast('Formulario válido. El registro se habilitará al conectar PHP/MySQL.');else showToast('La recuperación de contraseña se habilitará al conectar el backend.');})});
}
function openModal(title,body){modalContent.innerHTML=`<h2 id="modalTitle">${title}</h2>${body}`;modal.hidden=false}
function closeModal(){modal.hidden=true}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const name=b.dataset.name,action=b.dataset.action;if(action==='room'){const r=roomTypes.find(x=>x.name===name);if(r)openModal(r.name,`<img class="card-image" src="${r.img}" alt="${r.name}"><p>${r.details}</p><div class="room-meta"><div><div class="price-label">DESDE</div><div class="price">${money(r.price)}</div><small>/ noche</small></div><a class="btn" href="#inicio" onclick="closeModal()">Consultar disponibilidad</a></div><p class="notice">Las tarifas mostradas son de referencia. La disponibilidad se confirmará al conectar el sistema.</p>`)}else if(action==='amenity'){const x=amenities.find(a=>a.name===name);openModal(name,`<img class="card-image" src="${x.img}" alt="${name}"><p>${x.desc}</p><p>Consulta horarios y disponibilidad directamente con recepción durante tu estancia.</p><button class="btn" onclick="closeModal()">Entendido</button>`)}else if(action==='dish'){const d=dishes.find(x=>x.name===name);openModal(name,`<img class="card-image" src="${d.img}" alt="${name}"><p>${d.desc}</p><p class="notice">Consulta ingredientes, alérgenos y disponibilidad con el restaurante antes de ordenar.</p><button class="btn" onclick="closeModal()">Cerrar</button>`)}else if(action==='service'){const s=services.find(x=>x.name===name);openModal(name,`<img class="card-image" src="${s.img}" alt="${name}"><p>${s.desc}</p><p>La solicitud del servicio se habilitará cuando se conecte el sistema de reservas internas.</p><button class="btn" onclick="closeModal()">Entendido</button>`)}});
document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));window.addEventListener('hashchange',render);document.getElementById('year').textContent=new Date().getFullYear();render();
